#!/usr/bin/bash

###GENERATED BY ansible_helpers/conf_firewalld (https://github.com/vladimir-chursin000/ansible_helpers)

######INIT DIRS and FILES
SELF_DIR_str="$(dirname $(readlink -f $0))";
EXEC_RESULT_DIR_str="$SELF_DIR_str/../exec_results";
NOW_YYYYMMDDHHMISS_AT_START_str=`date '+%Y%m%d%H%M%S'`;
EXEC_RESULT_FILE_str="$EXEC_RESULT_DIR_str/$NOW_YYYYMMDDHHMISS_AT_START_str-check_ext_timeouts.log";
######INIT DIRS and FILES

######CFG
CONTENT_DIR_PWET_str="$SELF_DIR_str/../permanent_ipsets";
LIST_FILE_PWET_str="$CONTENT_DIR_str/LIST";
######CFG

######VARS
NEED_RELOAD_N_RESTORE_TMP_IPSETS_CONT_str='no';

LINE0_str='';
LINE1_str='';

declare -a TMP_arr;

EPOCH_TIME_NOW_num=0;
EPOCH_TIME_CFG_num=0;
TIMEOUT_num=0;
######VARS

######FUNCTIONS
function write_log_func() {
    local local_log_str=$1;
    local local_log_file_str=$2;
    local local_now_yyyymmddhhmiss_str=`date '+%Y%m%d%H%M%S'`;

    echo "$local_now_yyyymmddhhmiss_str;+$local_log_str" &>> $local_log_file_str;
}
######FUNCTIONS

######MAIN
if [[ -s "$LIST_FILE_PWET_str" ]]; then
    write_log_func "Read ipset-names with external timeout from file='$LIST_FILE_PWET_str'";
    
    while read -r LINE0_str; # LINE0_str = ipset_name
    do
        if [[ -s "/etc/firewalld/ipsets/$LINE0_str.xml" ]]; then # if file exists and not empty
            write_log_func "Check ipsets entries with external timeout from file='$CONTENT_DIR_PWET_str/$LINE0_str'";
	    
            while read -r LINE1_str; # LINE1_str = one line with ipset entry
            do
                TMP_arr=($(echo "$LINE1_str" | sed 's/;+/\n/g')); # 0=ip, 1=expire_dt_at_format_YYYYMMDDHHMISS (num)
		
                EPOCH_TIME_CFG_num=`date -d "$(echo ${TMP_arr[1]} | awk '{print substr($1,1,8), substr($1,9,2) ":" substr($1,11,2)":" substr($1,13,2)}')" '+%s'`;
                EPOCH_TIME_NOW_num=`date '+%s'`;
                TIMEOUT_num=$(($EPOCH_TIME_CFG_num - $EPOCH_TIME_NOW_num));
		
                if [[ "$TIMEOUT_num" -lt "1" ]]; then
                    write_log_func "Ipset entry '${TMP_arr[0]}' from file='$CONTENT_DIR_PWET_str/$LINE0_str' is EXPIRED. Removing it from ipset";
		    
                    firewall-cmd --permanent --ipset="$LINE0_str" --remove-entry="${TMP_arr[0]}";
		    
		    NEED_RELOAD_N_RESTORE_TMP_IPSETS_CONT_str='yes';
                fi;

                # clear vars
                TMP_arr=();
                EPOCH_TIME_NOW_num=0;
                EPOCH_TIME_CFG_num=0;
                TIMEOUT_num=0;
                ###
            done < "$CONTENT_DIR_PWET_str/$LINE0_str";
        fi;
    done < $LIST_FILE_PWET_str;
fi;

if [[ "$NEED_RELOAD_N_RESTORE_TMP_IPSETS_CONT_str" == "yes" ]]; then
    firewall-cmd --reload;
    
    "$SELF_DIR_str/restore_tmp_ipsets_content_after_reboot.sh";
fi;
######MAIN
