#!/usr/bin/bash

###GENERATED BY ansible_helpers/conf_firewalld (https://github.com/vladimir-chursin000/ansible_helpers)

touch ~/ansible_helpers/conf_firewalld/apply_ipset_lists_is_run_now;

rm -rf ~/ansible_helpers/conf_firewalld/apply_ipset_lists_is_run_now;