#!/usr/bin/bash

###GENERATED BY ansible_helpers/conf_firewalld (https://github.com/vladimir-chursin000/ansible_helpers)

SELF_DIR_str="$(dirname $(readlink -f $0))";
EXEC_RESULT_DIR_str="$SELF_DIR_str/exec_results";
NOW_YYYYMMDDHHMISS_AT_START_str=`date '+%Y%m%d%H%M%S'`;
EXEC_RESULT_FILE_str="$EXEC_RESULT_DIR_str/$NOW_YYYYMMDDHHMISS_AT_START_str-temporary_panic_on.log";

if [[ ! -d $EXEC_RESULT_DIR_str ]]; then
    mkdir -p "$EXEC_RESULT_DIR_str";
fi;

###VARS
TIMEOUT_num=$1;
NOW_YYYYMMDDHHMISS_str='';
###VARS

NOW_YYYYMMDDHHMISS_str=`date '+%Y%m%d%H%M%S'`;
echo "$NOW_YYYYMMDDHHMISS_str;+Set panic on" &>> $EXEC_RESULT_FILE_str;

while :
do
    NOW_YYYYMMDDHHMISS_str=`date '+%Y%m%d%H%M%S'`;
    echo "$NOW_YYYYMMDDHHMISS_str;+Wait iteration number $TIMEOUT_num" &>> $EXEC_RESULT_FILE_str;
     
    sleep 60;

    let "TIMEOUT_num-=1";
    
    if [[ "$TIMEOUT_num" -le "0" ]]; then
        NOW_YYYYMMDDHHMISS_str=`date '+%Y%m%d%H%M%S'`;
	echo "$NOW_YYYYMMDDHHMISS_str;+Set panic off" &>> $EXEC_RESULT_FILE_str;
	
	exit;
    fi;
done;
