#!/usr/bin/bash

###GENERATED BY ansible_helpers/conf_int_ipv4_via_network_scripts (https://github.com/vladimir-chursin000/ansible_helpers)

SELF_DIR="$(dirname $(readlink -f $0))";

###ARGV
TIMEOUT_num=$1;
###ARGV

###STATIC_VARS
IFCFG_BACKUP_DIR="~/ifcfg_backup_now";
IFCFG_DIR='/etc/sysconfig/networks-scripts';
###STATIC_VARS

while :
do
    sleep 60;

    let "TIMEOUT_num-=1";
    if [[ "$TIMEOUT_num" -le "0" ]]; then
	###DO ROLLBACK of ifcfg changes
	
	###DO ROLLBACK of ifcfg changes
	exit;	
    fi;
done;
