#!/usr/bin/bash

###GENERATED BY ansible_helpers/install_nfs_server (https://github.com/vladimir-chursin000/ansible_helpers)

SELF_DIR="$(dirname $(readlink -f $0))";
EXPORTS_FILE="/etc/exports";

###CFG
NFS_SHARE_CHMOD=777;
###CFG

###VARS
LINE='';
EXE_RES='';
###VARS

while read LINE; do 
    LINE=`echo $LINE | sed -r 's/\s+\S+\(*//'`;
    if [ ! -z "$LINE" ]; then
	EXE_RES=`mkdir -p $LINE`;
	EXE_RES=`chmod $NFS_SHARE_CHMOD $LINE`;
	EXE_RES=`chmod +t $LINE`;
    fi;
done < "$EXPORTS_FILE";
